[2025-10-22T15:37:22.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-22T15:37:23.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:37:10.254087+00:00 [queued]>
[2025-10-22T15:37:23.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:37:10.254087+00:00 [queued]>
[2025-10-22T15:37:23.069+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-22T15:37:23.117+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): soda_test_core> on 2025-10-22 15:37:10.254087+00:00
[2025-10-22T15:37:23.143+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_quality', 'soda_test_core', 'manual__2025-10-22T15:37:10.254087+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpgzr1l8kb']
[2025-10-22T15:37:23.143+0000] {standard_task_runner.py:63} INFO - Started process 2248 to run task
[2025-10-22T15:37:23.147+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask soda_test_core
[2025-10-22T15:37:23.344+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:37:10.254087+00:00 [running]> on host 5adcf1b12c4a
[2025-10-22T15:37:23.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gidiboateng200@gmail.com' AIRFLOW_CTX_DAG_OWNER='dataengineers' AIRFLOW_CTX_DAG_ID='data_quality' AIRFLOW_CTX_TASK_ID='soda_test_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-22T15:37:10.254087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-22T15:37:10.254087+00:00'
[2025-10-22T15:37:23.673+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-22T15:37:23.682+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-22T15:37:23.688+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d pg_datasource -c /opt/airflow/include/soda/configuration.yml -v SCHEMA=core /opt/airflow/include/soda/checks.yml']
[2025-10-22T15:37:23.727+0000] {subprocess.py:86} INFO - Output:
[2025-10-22T15:37:28.060+0000] {subprocess.py:93} INFO - [15:37:28] Soda Core 3.3.14
[2025-10-22T15:37:28.424+0000] {subprocess.py:93} INFO - [15:37:28] Scan summary:
[2025-10-22T15:37:28.427+0000] {subprocess.py:93} INFO - [15:37:28] 4/4 checks PASSED:
[2025-10-22T15:37:28.431+0000] {subprocess.py:93} INFO - [15:37:28]     yt_api in pg_datasource
[2025-10-22T15:37:28.436+0000] {subprocess.py:93} INFO - [15:37:28]       Check for Like_Count greater than Video_Views [PASSED]
[2025-10-22T15:37:28.438+0000] {subprocess.py:93} INFO - [15:37:28]       Check for Comments_Count greater than Video_Views [PASSED]
[2025-10-22T15:37:28.449+0000] {subprocess.py:93} INFO - [15:37:28]       missing_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:37:28.454+0000] {subprocess.py:93} INFO - [15:37:28]       duplicate_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:37:28.470+0000] {subprocess.py:93} INFO - [15:37:28] All is good. No failures. No warnings. No errors.
[2025-10-22T15:37:29.411+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-22T15:37:29.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-22T15:37:29.489+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_quality, task_id=soda_test_core, run_id=manual__2025-10-22T15:37:10.254087+00:00, execution_date=20251022T153710, start_date=20251022T153723, end_date=20251022T153729
[2025-10-22T15:37:29.614+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-22T15:37:29.642+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
