[2025-10-22T15:20:20.607+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-22T15:20:20.691+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:20:10.681191+00:00 [queued]>
[2025-10-22T15:20:20.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:20:10.681191+00:00 [queued]>
[2025-10-22T15:20:20.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-22T15:20:20.764+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): soda_test_core> on 2025-10-22 15:20:10.681191+00:00
[2025-10-22T15:20:20.795+0000] {standard_task_runner.py:63} INFO - Started process 2014 to run task
[2025-10-22T15:20:20.806+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_quality', 'soda_test_core', 'manual__2025-10-22T15:20:10.681191+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6_shbuh8']
[2025-10-22T15:20:20.817+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask soda_test_core
[2025-10-22T15:20:21.015+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality.soda_test_core manual__2025-10-22T15:20:10.681191+00:00 [running]> on host 5adcf1b12c4a
[2025-10-22T15:20:21.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gidiboateng200@gmail.com' AIRFLOW_CTX_DAG_OWNER='dataengineers' AIRFLOW_CTX_DAG_ID='data_quality' AIRFLOW_CTX_TASK_ID='soda_test_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-22T15:20:10.681191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-22T15:20:10.681191+00:00'
[2025-10-22T15:20:21.246+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-22T15:20:21.257+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-22T15:20:21.260+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d pg_datasource -c /opt/airflow/include/soda/configuration.yml -v SCHEMA=core /opt/airflow/include/soda/checks.yml']
[2025-10-22T15:20:21.300+0000] {subprocess.py:86} INFO - Output:
[2025-10-22T15:20:25.557+0000] {subprocess.py:93} INFO - [15:20:25] Soda Core 3.3.14
[2025-10-22T15:20:25.803+0000] {subprocess.py:93} INFO - [15:20:25] Scan summary:
[2025-10-22T15:20:25.804+0000] {subprocess.py:93} INFO - [15:20:25] 4/4 checks PASSED:
[2025-10-22T15:20:25.804+0000] {subprocess.py:93} INFO - [15:20:25]     yt_api in pg_datasource
[2025-10-22T15:20:25.805+0000] {subprocess.py:93} INFO - [15:20:25]       Check for Like_Count greater than Video_Views [PASSED]
[2025-10-22T15:20:25.806+0000] {subprocess.py:93} INFO - [15:20:25]       Check for Comments_Count greater than Video_Views [PASSED]
[2025-10-22T15:20:25.807+0000] {subprocess.py:93} INFO - [15:20:25]       missing_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:20:25.808+0000] {subprocess.py:93} INFO - [15:20:25]       duplicate_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:20:25.809+0000] {subprocess.py:93} INFO - [15:20:25] All is good. No failures. No warnings. No errors.
[2025-10-22T15:20:26.545+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-22T15:20:26.551+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-22T15:20:26.614+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_quality, task_id=soda_test_core, run_id=manual__2025-10-22T15:20:10.681191+00:00, execution_date=20251022T152010, start_date=20251022T152020, end_date=20251022T152026
[2025-10-22T15:20:26.674+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-22T15:20:26.725+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-22T15:20:26.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
