[2025-10-18T10:16:54.665+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/main.py
[2025-10-18T10:16:54.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:16:54.710+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:16:54.708+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:16:54.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:16:54.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.377 seconds
[2025-10-18T10:17:25.761+0000] {processor.py:161} INFO - Started process (PID=841) to work on /opt/airflow/dags/main.py
[2025-10-18T10:17:25.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:17:25.771+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:17:25.770+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:17:25.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:17:25.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.082 seconds
[2025-10-18T10:17:27.830+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/main.py
[2025-10-18T10:17:27.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:17:27.865+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:17:27.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:17:28.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:17:29.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.207 seconds
[2025-10-18T10:17:59.617+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/main.py
[2025-10-18T10:17:59.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:17:59.625+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:17:59.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:17:59.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:17:59.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.144 seconds
[2025-10-18T10:18:30.497+0000] {processor.py:161} INFO - Started process (PID=856) to work on /opt/airflow/dags/main.py
[2025-10-18T10:18:30.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:18:30.515+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:18:30.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:18:30.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:18:30.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.486 seconds
[2025-10-18T10:19:02.138+0000] {processor.py:161} INFO - Started process (PID=863) to work on /opt/airflow/dags/main.py
[2025-10-18T10:19:02.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:19:02.178+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:19:02.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:19:03.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:19:03.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.227 seconds
[2025-10-18T10:19:33.877+0000] {processor.py:161} INFO - Started process (PID=876) to work on /opt/airflow/dags/main.py
[2025-10-18T10:19:33.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:19:33.920+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:19:33.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:19:34.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:19:34.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.320 seconds
[2025-10-18T10:20:04.318+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/main.py
[2025-10-18T10:20:04.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:20:04.335+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:20:04.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:20:04.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:20:04.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.359 seconds
[2025-10-18T10:20:34.953+0000] {processor.py:161} INFO - Started process (PID=890) to work on /opt/airflow/dags/main.py
[2025-10-18T10:20:34.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:20:34.959+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:20:34.958+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:20:35.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:20:35.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.171 seconds
[2025-10-18T10:21:05.854+0000] {processor.py:161} INFO - Started process (PID=896) to work on /opt/airflow/dags/main.py
[2025-10-18T10:21:05.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:21:05.872+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:21:05.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:21:06.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:21:06.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.216 seconds
[2025-10-18T10:21:36.870+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/main.py
[2025-10-18T10:21:36.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:21:36.892+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:21:36.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:21:37.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:21:37.268+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.423 seconds
[2025-10-18T10:22:07.929+0000] {processor.py:161} INFO - Started process (PID=910) to work on /opt/airflow/dags/main.py
[2025-10-18T10:22:07.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:22:07.938+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:22:07.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:22:08.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:22:08.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.317 seconds
[2025-10-18T10:22:38.999+0000] {processor.py:161} INFO - Started process (PID=917) to work on /opt/airflow/dags/main.py
[2025-10-18T10:22:39.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:22:39.016+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:22:39.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:22:39.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:22:39.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.337 seconds
[2025-10-18T10:23:09.995+0000] {processor.py:161} INFO - Started process (PID=924) to work on /opt/airflow/dags/main.py
[2025-10-18T10:23:10.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:23:10.014+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:23:10.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:23:10.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:23:10.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.380 seconds
[2025-10-18T10:23:40.986+0000] {processor.py:161} INFO - Started process (PID=931) to work on /opt/airflow/dags/main.py
[2025-10-18T10:23:41.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:23:41.027+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:23:41.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:23:41.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:23:41.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.440 seconds
[2025-10-18T10:24:11.859+0000] {processor.py:161} INFO - Started process (PID=938) to work on /opt/airflow/dags/main.py
[2025-10-18T10:24:11.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:24:11.868+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:24:11.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:24:11.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:24:11.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.153 seconds
[2025-10-18T10:24:42.467+0000] {processor.py:161} INFO - Started process (PID=945) to work on /opt/airflow/dags/main.py
[2025-10-18T10:24:42.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:24:42.474+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:24:42.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:24:42.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:24:42.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.149 seconds
[2025-10-18T10:25:13.176+0000] {processor.py:161} INFO - Started process (PID=952) to work on /opt/airflow/dags/main.py
[2025-10-18T10:25:13.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:25:13.185+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:25:13.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:25:13.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:25:13.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.244 seconds
[2025-10-18T10:25:43.743+0000] {processor.py:161} INFO - Started process (PID=958) to work on /opt/airflow/dags/main.py
[2025-10-18T10:25:43.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:25:43.788+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:25:43.787+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:25:44.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:25:44.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.579 seconds
[2025-10-18T10:26:14.709+0000] {processor.py:161} INFO - Started process (PID=965) to work on /opt/airflow/dags/main.py
[2025-10-18T10:26:14.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:26:14.744+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:26:14.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:26:15.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:26:15.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.354 seconds
[2025-10-18T10:26:45.925+0000] {processor.py:161} INFO - Started process (PID=973) to work on /opt/airflow/dags/main.py
[2025-10-18T10:26:45.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:26:45.941+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:26:45.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:26:46.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:26:46.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.330 seconds
[2025-10-18T10:27:16.666+0000] {processor.py:161} INFO - Started process (PID=980) to work on /opt/airflow/dags/main.py
[2025-10-18T10:27:16.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:27:16.672+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:27:16.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:27:16.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:27:16.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.136 seconds
[2025-10-18T10:27:47.459+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/main.py
[2025-10-18T10:27:47.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:27:47.465+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:27:47.464+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:27:47.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:27:47.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.137 seconds
[2025-10-18T10:28:18.081+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/main.py
[2025-10-18T10:28:18.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:28:18.125+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:28:18.125+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:28:19.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:28:19.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.001 seconds
[2025-10-18T10:28:49.627+0000] {processor.py:161} INFO - Started process (PID=1002) to work on /opt/airflow/dags/main.py
[2025-10-18T10:28:49.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:28:49.647+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:28:49.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:28:49.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:28:49.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.168 seconds
[2025-10-18T10:29:20.048+0000] {processor.py:161} INFO - Started process (PID=1009) to work on /opt/airflow/dags/main.py
[2025-10-18T10:29:20.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:29:20.055+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:29:20.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:29:20.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:29:20.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.140 seconds
[2025-10-18T10:29:50.360+0000] {processor.py:161} INFO - Started process (PID=1016) to work on /opt/airflow/dags/main.py
[2025-10-18T10:29:50.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:29:50.387+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:29:50.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:29:50.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:29:50.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.231 seconds
[2025-10-18T10:30:20.857+0000] {processor.py:161} INFO - Started process (PID=1023) to work on /opt/airflow/dags/main.py
[2025-10-18T10:30:20.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:30:20.863+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:30:20.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:30:20.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:30:20.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.105 seconds
[2025-10-18T10:30:51.507+0000] {processor.py:161} INFO - Started process (PID=1030) to work on /opt/airflow/dags/main.py
[2025-10-18T10:30:51.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:30:51.512+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:30:51.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:30:51.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:30:51.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.133 seconds
[2025-10-18T10:31:13.833+0000] {processor.py:161} INFO - Started process (PID=1037) to work on /opt/airflow/dags/main.py
[2025-10-18T10:31:13.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:31:13.848+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:31:13.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:31:14.265+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:31:14.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:31:14.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:31:14.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.556 seconds
[2025-10-18T10:31:44.490+0000] {processor.py:161} INFO - Started process (PID=1044) to work on /opt/airflow/dags/main.py
[2025-10-18T10:31:44.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:31:44.496+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:31:44.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:31:44.524+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:31:44.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:31:44.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:31:44.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.082 seconds
[2025-10-18T10:32:15.233+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/main.py
[2025-10-18T10:32:15.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:32:15.252+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:32:15.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:32:15.451+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:32:15.402+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:32:15.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:32:15.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.349 seconds
[2025-10-18T10:32:46.483+0000] {processor.py:161} INFO - Started process (PID=1058) to work on /opt/airflow/dags/main.py
[2025-10-18T10:32:46.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:32:46.502+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:32:46.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:32:46.545+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:32:46.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:32:46.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:32:46.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.151 seconds
[2025-10-18T10:33:17.049+0000] {processor.py:161} INFO - Started process (PID=1065) to work on /opt/airflow/dags/main.py
[2025-10-18T10:33:17.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:33:17.057+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:33:17.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:33:17.095+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:33:17.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:33:17.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:33:17.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.108 seconds
[2025-10-18T10:33:47.371+0000] {processor.py:161} INFO - Started process (PID=1073) to work on /opt/airflow/dags/main.py
[2025-10-18T10:33:47.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T10:33:47.378+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:33:47.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T10:33:47.410+0000] {logging_mixin.py:188} INFO - [2025-10-18T10:33:47.403+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T10:33:47.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T10:33:47.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2025-10-18T16:38:28.869+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/main.py
[2025-10-18T16:38:28.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:38:28.886+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:38:28.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:38:28.922+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:38:28.913+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:38:28.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:38:28.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.162 seconds
[2025-10-18T16:39:00.559+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/main.py
[2025-10-18T16:39:00.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:39:00.658+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:39:00.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:39:01.546+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:39:01.456+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:39:01.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:39:01.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.416 seconds
[2025-10-18T16:39:38.907+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/main.py
[2025-10-18T16:39:38.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:39:38.939+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:39:38.935+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:39:40.667+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:39:40.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:39:40.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:39:42.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 3.796 seconds
[2025-10-18T16:40:15.309+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/main.py
[2025-10-18T16:40:15.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:40:15.450+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:40:15.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:40:16.426+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:40:16.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:40:16.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:40:16.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.485 seconds
[2025-10-18T16:40:47.339+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/main.py
[2025-10-18T16:40:47.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:40:47.373+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:40:47.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:40:47.427+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:40:47.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:40:47.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:40:47.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.184 seconds
[2025-10-18T16:41:17.956+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/main.py
[2025-10-18T16:41:17.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:41:17.973+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:41:17.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:41:18.287+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:41:18.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:41:18.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:41:18.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.500 seconds
[2025-10-18T16:41:49.207+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/main.py
[2025-10-18T16:41:49.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:41:49.243+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:41:49.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:41:49.507+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:41:49.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:41:49.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:41:49.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.458 seconds
[2025-10-18T16:42:19.835+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/main.py
[2025-10-18T16:42:19.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:42:19.844+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:42:19.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:42:19.928+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:42:19.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:42:19.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:42:19.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.174 seconds
[2025-10-18T16:42:50.877+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/main.py
[2025-10-18T16:42:50.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:42:50.906+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:42:50.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:42:51.106+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:42:51.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:42:51.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:42:51.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.361 seconds
[2025-10-18T16:43:21.578+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/main.py
[2025-10-18T16:43:21.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:43:21.609+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:43:21.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:43:21.972+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:43:21.917+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:43:21.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:43:22.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.532 seconds
[2025-10-18T16:43:52.700+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/main.py
[2025-10-18T16:43:52.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:43:52.724+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:43:52.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:43:53.047+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:43:53.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:43:53.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:43:53.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.538 seconds
[2025-10-18T16:44:23.638+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/main.py
[2025-10-18T16:44:23.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:44:23.657+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:44:23.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:44:24.058+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:44:23.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:44:24.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:44:24.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.583 seconds
[2025-10-18T16:44:55.089+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/main.py
[2025-10-18T16:44:55.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:44:55.101+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:44:55.097+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:44:55.139+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:44:55.131+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:44:55.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:44:55.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.110 seconds
[2025-10-18T16:45:25.750+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/main.py
[2025-10-18T16:45:25.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:45:25.771+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:45:25.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:45:25.854+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:45:25.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:45:25.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:45:25.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.217 seconds
[2025-10-18T16:45:56.414+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/main.py
[2025-10-18T16:45:56.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:45:56.424+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:45:56.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:45:56.469+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:45:56.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:45:56.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:45:56.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.163 seconds
[2025-10-18T16:46:27.132+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/main.py
[2025-10-18T16:46:27.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:46:27.139+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:46:27.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:46:27.194+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:46:27.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:46:27.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:46:27.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.146 seconds
[2025-10-18T16:46:57.638+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/main.py
[2025-10-18T16:46:57.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:46:57.644+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:46:57.644+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:46:57.689+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:46:57.679+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:46:57.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:46:57.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.118 seconds
[2025-10-18T16:47:28.816+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/main.py
[2025-10-18T16:47:28.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:47:28.833+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:47:28.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:47:28.872+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:47:28.865+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:47:28.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:47:28.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.171 seconds
[2025-10-18T16:47:59.470+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/main.py
[2025-10-18T16:47:59.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:47:59.477+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:47:59.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:47:59.530+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:47:59.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:47:59.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:47:59.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.135 seconds
[2025-10-18T16:48:30.245+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/main.py
[2025-10-18T16:48:30.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:48:30.264+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:48:30.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:48:30.485+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:48:30.438+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:48:30.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:48:30.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.369 seconds
[2025-10-18T16:49:00.982+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/main.py
[2025-10-18T16:49:00.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:49:00.989+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:49:00.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:49:01.020+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:49:01.013+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:49:01.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:49:01.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.094 seconds
[2025-10-18T16:49:31.516+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/main.py
[2025-10-18T16:49:31.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:49:31.525+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:49:31.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:49:31.619+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:49:31.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:49:31.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:49:31.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.211 seconds
[2025-10-18T16:50:02.495+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/main.py
[2025-10-18T16:50:02.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:50:02.555+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:50:02.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:50:02.750+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:50:02.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:50:02.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:50:03.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.557 seconds
[2025-10-18T16:50:34.033+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/main.py
[2025-10-18T16:50:34.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:50:34.040+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:50:34.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:50:34.160+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:50:34.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:50:34.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:50:34.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.304 seconds
[2025-10-18T16:51:05.428+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/main.py
[2025-10-18T16:51:05.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:51:05.458+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:51:05.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:51:05.559+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:51:05.542+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:51:05.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:51:05.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.307 seconds
[2025-10-18T16:51:36.344+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/main.py
[2025-10-18T16:51:36.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:51:36.383+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:51:36.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:51:36.522+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:51:36.510+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:51:36.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:51:36.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.337 seconds
[2025-10-18T16:53:42.744+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/main.py
[2025-10-18T16:53:42.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T16:53:42.778+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:53:42.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T16:53:43.159+0000] {logging_mixin.py:188} INFO - [2025-10-18T16:53:43.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T16:53:43.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T16:53:43.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.542 seconds
[2025-10-18T19:04:10.598+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/main.py
[2025-10-18T19:04:11.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2025-10-18T19:04:11.242+0000] {logging_mixin.py:188} INFO - [2025-10-18T19:04:11.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2025-10-18T19:04:11.364+0000] {logging_mixin.py:188} INFO - [2025-10-18T19:04:11.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 1, in <module>
    from airflow.sdk import DAG
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-10-18T19:04:11.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2025-10-18T19:04:11.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.861 seconds
