[2025-10-22T15:20:13.019+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-22T15:20:13.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality.soda_test_staging manual__2025-10-22T15:20:10.681191+00:00 [queued]>
[2025-10-22T15:20:13.118+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality.soda_test_staging manual__2025-10-22T15:20:10.681191+00:00 [queued]>
[2025-10-22T15:20:13.137+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-22T15:20:13.188+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): soda_test_staging> on 2025-10-22 15:20:10.681191+00:00
[2025-10-22T15:20:13.202+0000] {standard_task_runner.py:63} INFO - Started process 2002 to run task
[2025-10-22T15:20:13.211+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_quality', 'soda_test_staging', 'manual__2025-10-22T15:20:10.681191+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpjafmtbit']
[2025-10-22T15:20:13.217+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask soda_test_staging
[2025-10-22T15:20:13.381+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality.soda_test_staging manual__2025-10-22T15:20:10.681191+00:00 [running]> on host 5adcf1b12c4a
[2025-10-22T15:20:13.555+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gidiboateng200@gmail.com' AIRFLOW_CTX_DAG_OWNER='dataengineers' AIRFLOW_CTX_DAG_ID='data_quality' AIRFLOW_CTX_TASK_ID='soda_test_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-10-22T15:20:10.681191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-22T15:20:10.681191+00:00'
[2025-10-22T15:20:13.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-22T15:20:13.559+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-22T15:20:13.562+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d pg_datasource -c /opt/airflow/include/soda/configuration.yml -v SCHEMA=staging /opt/airflow/include/soda/checks.yml']
[2025-10-22T15:20:13.582+0000] {subprocess.py:86} INFO - Output:
[2025-10-22T15:20:16.728+0000] {subprocess.py:93} INFO - [15:20:16] Soda Core 3.3.14
[2025-10-22T15:20:16.995+0000] {subprocess.py:93} INFO - [15:20:16] Scan summary:
[2025-10-22T15:20:16.996+0000] {subprocess.py:93} INFO - [15:20:16] 4/4 checks PASSED:
[2025-10-22T15:20:16.997+0000] {subprocess.py:93} INFO - [15:20:16]     yt_api in pg_datasource
[2025-10-22T15:20:16.998+0000] {subprocess.py:93} INFO - [15:20:16]       Check for Like_Count greater than Video_Views [PASSED]
[2025-10-22T15:20:16.999+0000] {subprocess.py:93} INFO - [15:20:16]       Check for Comments_Count greater than Video_Views [PASSED]
[2025-10-22T15:20:17.000+0000] {subprocess.py:93} INFO - [15:20:16]       missing_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:20:17.000+0000] {subprocess.py:93} INFO - [15:20:16]       duplicate_count("Video_ID") = 0 [PASSED]
[2025-10-22T15:20:17.001+0000] {subprocess.py:93} INFO - [15:20:16] All is good. No failures. No warnings. No errors.
[2025-10-22T15:20:17.752+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-22T15:20:17.755+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-22T15:20:17.817+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_quality, task_id=soda_test_staging, run_id=manual__2025-10-22T15:20:10.681191+00:00, execution_date=20251022T152010, start_date=20251022T152013, end_date=20251022T152017
[2025-10-22T15:20:17.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-22T15:20:17.932+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-22T15:20:17.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
